export const EVENT_LOGGER_INFO = 'EVENT.LOGGER.INFO';
export const EVENT_LOGGER_WARN = 'EVENT.LOGGER.WARN';
export const EVENT_LOGGER_ERROR = 'EVENT.LOGGER.ERROR';
export const EVENT_LOGGER_CRITICAL = 'EVENT.LOGGER.CRITICAL';